// <auto-generated />
using System;
using CalculatorApi.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CalculatorApi.Migrations
{
    [DbContext(typeof(CalculatorContext))]
    [Migration("20190803081015_CalculatorApi.EF.CalculatorContext")]
    partial class CalculatorApiEFCalculatorContext
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CalculatorApi.Entities.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("CalculatorApi.Entities.CountryWeekend", b =>
                {
                    b.Property<int>("CountryId");

                    b.Property<int>("DayOfWeekId");

                    b.HasKey("CountryId", "DayOfWeekId");

                    b.HasIndex("DayOfWeekId");

                    b.ToTable("CountryWeekends");
                });

            modelBuilder.Entity("CalculatorApi.Entities.DayOfWeek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Day");

                    b.HasKey("Id");

                    b.ToTable("WeekEnds");
                });

            modelBuilder.Entity("CalculatorApi.Entities.Holiday", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CountryId");

                    b.Property<int>("Day");

                    b.Property<int>("Month");

                    b.Property<int>("Year");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Holidays");
                });

            modelBuilder.Entity("CalculatorApi.Entities.CountryWeekend", b =>
                {
                    b.HasOne("CalculatorApi.Entities.Country", "Country")
                        .WithMany("Weekends")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CalculatorApi.Entities.DayOfWeek", "DayOfWeek")
                        .WithMany("Countries")
                        .HasForeignKey("DayOfWeekId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CalculatorApi.Entities.Holiday", b =>
                {
                    b.HasOne("CalculatorApi.Entities.Country")
                        .WithMany("Holidays")
                        .HasForeignKey("CountryId");
                });
#pragma warning restore 612, 618
        }
    }
}
